SERVER = tftp-server
CLIENT = tftp-client

CC = gcc
# CXX = g++
CFLAGS = -Wall -Wextra -std=c11
LDLIBS =

SRCS = $(wildcard *.c)

.PHONY: clean all

all: $(SERVER) $(CLIENT)

$(SERVER):

$(CLIENT):

clean:
	rm -f $(SERVER) $(CLIENT)

